import { defineConfig } from "oxlint";

export default defineConfig({
  plugins: [
    "eslint",
    "typescript",
    "unicorn",
    "oxc",
    "import",
    "react",
    "jsx-a11y",
    "react-perf",
    "promise",
  ],
  categories: {
    correctness: "error",
    suspicious: "error",
    perf: "warn",
  },
  env: {
    browser: true,
    es2024: true,
    node: true,
  },
  options: {
    typeAware: true,
  },
  ignorePatterns: ["dist", ".astro"],
  rules: {
    "array-callback-return": "error",
    "curly": "error",
    "eqeqeq": ["error", "always", { null: "ignore" }],
    "no-alert": "error",
    "no-console": ["warn", { allow: ["warn", "error"] }],
    "no-debugger": "error",
    "no-implicit-coercion": "error",
    "no-promise-executor-return": "error",
    "no-undef": "error",
    "no-unused-vars": "error",
    "no-var": "error",
    "prefer-const": "error",
    "prefer-template": "warn",

    "import/export": "error",
    "import/named": "error",
    "import/namespace": "error",
    "import/no-cycle": "error",

    "jsx-a11y/alt-text": "error",
    "jsx-a11y/anchor-is-valid": "error",
    "jsx-a11y/click-events-have-key-events": "error",
    "jsx-a11y/no-autofocus": "warn",
    "jsx-a11y/no-static-element-interactions": "error",

    "promise/always-return": "error",
    "promise/catch-or-return": "error",
    "promise/no-nesting": "warn",
    "promise/no-return-wrap": "error",
    "promise/param-names": "error",

    "react/checked-requires-onchange-or-readonly": "error",
    "react/exhaustive-deps": "error",
    "react/iframe-missing-sandbox": "error",
    "react/jsx-key": "error",
    "react/jsx-no-constructed-context-values": "error",
    "react/jsx-no-duplicate-props": "error",
    "react/jsx-no-script-url": "error",
    "react/jsx-no-target-blank": "error",
    "react/jsx-no-undef": "error",
    "react/no-array-index-key": "warn",
    "react/no-danger": "error",
    "react/no-danger-with-children": "error",
    "react/no-direct-mutation-state": "error",
    "react/no-unknown-property": "error",
    "react/no-unstable-nested-components": "warn",
    "react/react-in-jsx-scope": "off",
    "react/rules-of-hooks": "error",

    "typescript/consistent-type-assertions": "error",
    "typescript/consistent-type-definitions": ["warn", "interface"],
    "typescript/consistent-type-exports": "warn",
    "typescript/consistent-type-imports": "error",
    "typescript/no-confusing-non-null-assertion": "error",
    "typescript/no-deprecated": "warn",
    "typescript/no-duplicate-enum-values": "error",
    "typescript/no-duplicate-type-constituents": "error",
    "typescript/no-empty-object-type": "error",
    "typescript/no-explicit-any": "error",
    "typescript/no-extra-non-null-assertion": "error",
    "typescript/no-floating-promises": "error",
    "typescript/no-for-in-array": "error",
    "typescript/no-import-type-side-effects": "error",
    "typescript/no-misused-promises": "error",
    "typescript/no-misused-spread": "error",
    "typescript/no-non-null-asserted-nullish-coalescing": "error",
    "typescript/no-non-null-asserted-optional-chain": "error",
    "typescript/no-non-null-assertion": "warn",
    "typescript/no-require-imports": "error",
    "typescript/no-unnecessary-condition": "warn",
    "typescript/no-unnecessary-type-assertion": "warn",
    "typescript/no-unsafe-argument": "error",
    "typescript/no-unsafe-assignment": "error",
    "typescript/no-unsafe-call": "error",
    "typescript/no-unsafe-member-access": "error",
    "typescript/no-unsafe-return": "error",
    "typescript/no-unsafe-type-assertion": "error",
    "typescript/prefer-as-const": "error",
    "typescript/prefer-find": "warn",
    "typescript/prefer-for-of": "warn",
    "typescript/prefer-includes": "warn",
    "typescript/prefer-nullish-coalescing": "warn",
    "typescript/prefer-optional-chain": "warn",
    "typescript/promise-function-async": "warn",
    "typescript/require-array-sort-compare": "error",
    "typescript/require-await": "error",
    "typescript/restrict-plus-operands": "error",
    "typescript/restrict-template-expressions": "error",
    "typescript/strict-boolean-expressions": "error",
    "typescript/switch-exhaustiveness-check": "error",
    "typescript/unbound-method": "error",
  },
});
